import type { Metadata } from 'next';
import { Hanken_Grotesk, Inter } from 'next/font/google';
import StyledComponentRegistry from '@/lib/registery';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });
const hankenGrotesk = Hanken_Grotesk({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  console.log(params, 'params');
  return (
    <html lang='en'>
      <Head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          type='crossorigin'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Hanken+Grotesk:ital,wght@0,100;0,200;1,100;1,200&display=swap'
          rel='stylesheet'
        />
      </Head>
      <body className={hankenGrotesk.className}>
        <StyledComponentRegistry>{children}</StyledComponentRegistry>
      </body>
    </html>
  );
}
